### ISSUE TITLE
Trouble running this on Android

### ISSUE THREAD

**Issue by thatnerdjosh** [maherzaidoune/RNUrlPreviewExample#9]
https://github.com/facebook/react-native/issues/25371

I am getting the same issue that is described in that post... tried debugging for over an hour and no luck, any ideas?

**Comment by maherzaidoune** [comment]
i'll take a look at this tonight

**Comment by thatnerdjosh** [comment]
Were you able to reproduce it?

**Comment by maherzaidoune** [comment]
> Were you able to reproduce it?

not yet , sorry, I've been quite busy

**Comment by thatnerdjosh** [comment]
@maherzaidoune Just a quick ping on this :)

**Comment by maherzaidoune** [comment]
> @maherzaidoune Just a quick ping on this :)

fixed :)
